# Generated by Django 3.2.9 on 2021-12-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='watts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
