# Generated by Django 3.2.9 on 2021-12-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_watts'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
