# Generated by Django 3.2.9 on 2021-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwh_price', models.IntegerField()),
                ('currency_name', models.CharField(max_length=150)),
                ('currency_abbr', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
