# Generated by Django 3.2.9 on 2021-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='kwh_price',
            field=models.FloatField(),
        ),
    ]
